version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    target-branch: main
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Taipei
    open-pull-requests-limit: 5
    groups:
      production-minor-and-patch:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-minor-and-patch:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: main
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Taipei
    open-pull-requests-limit: 5
    groups:
      actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
