name: alphabiz
title: Alphabiz
version: 0.2.1-nightly-202302041621
summary: Alphabiz Blockchain Cryptocurrency Application
description: Alphabiz Blockchain Cryptocurrency Application
grade: stable
confinement: strict
base: core18

apps:
  alphabiz:
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - mount-observe
      - network
      - network-bind
      - unity7
      - x11
      - browser-support
      - wayland
    extensions: [gnome-3-28]
    command: bin/desktop-launch $SNAP/alphabiz/Alphabiz --no-sandbox

parts:
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-type: git
    source-depth: 1
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - gcc
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform

  alphabiz:
    source: out/make/snapcraft
    after:
      - desktop-gnome-platform
    source-type: local
    plugin: dump
    build-packages:
      - libasound2
    stage-packages:
      - libnotify4
      - libnss3
      - libpcre3
      - libxss1
      - libxtst6
      - libdrm2
      - libgbm1
      - libwayland-server0
      - libasound2
    organize:
      Alphabiz: alphabiz

plugs:
  gnome-3-28-1804:
    default-provider: gnome-3-28-1804
    interface: content
    target: $SNAP/gnome-platform
  gtk-3-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/themes
  icon-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/icons
  sound-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/sounds
